### ISSUE TITLE
Support macOS 12.3 and newer

### ISSUE THREAD

**Issue by DudeNr33** [DudeNr33/screen-on-time#2]
macOS 12.3 removed support for Python 2.7.
Hence the direct invocation of the script through `./scree_on_time.py` fails:
```shell
zsh: /Users/andreas/programming/oss_projects/screen-on-time/src/screen_on_time.py: bad interpreter: /usr/bin/python: no such file or directory
```

**Comment by hotrungnhan** [comment]
set an alias of python 3 to python.

**Comment by DudeNr33** [comment]
Thanks @hotrungnhan for the suggestion, that would be an easy workaround!

**Comment by DudeNr33** [comment]
Python 3 now supported through https://github.com/DudeNr33/screen-on-time/commit/23d83358dc12806501729774ca812edb32887d99. 
Python 2 version available in branch `python2`.
