### ISSUE TITLE
Doccument improve : fast run script by using cli

### ISSUE THREAD

**Issue by hotrungnhan** [DudeNr33/screen-on-time#3]
we can run this by one command 
``` bash
curl -s https://raw.githubusercontent.com/DudeNr33/screen-on-time/main/src/screen_on_time.py | python -s
```
another issue is compatible: this script can run well in newer macos  if we set alias of python3 to python.

**Comment by DudeNr33** [comment]
Thanks, I will add it to the readme!

**Comment by DudeNr33** [comment]
Added in https://github.com/DudeNr33/screen-on-time/commit/2e4cfca80624303e2e51c1ddfa11fbed480deae8
