### ISSUE TITLE
invalid active developer path

### ISSUE THREAD

**Issue by deonisy** [DudeNr33/screen-on-time#4]
Hello! Great tool. When running the code via Terminal I get an error:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Previously ran without problems.
Please help me fix it.

**Comment by DudeNr33** [comment]
Hi @deonisy,

did you by any chance update your macOS version recently?
This looks like a general `xcode` problem. [This stackoverflow question](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa) has a few possible solutions. 

Could you try to follow the instructions of the first answer and see if this helps?

**Comment by deonisy** [comment]
Hi, Andreas! Yes, I've updated macOS and that's why that problem happened and started suspecting it right away.
After installing Command-line Tools the problem was resolved.

Thank you very much for your help :)

**Comment by DudeNr33** [comment]
Glad that I could help! 😊
