### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by shoaibhussain-uc** [DudeNr33/screen-on-time#5]
Hi, this script is not giving the correct total screen-on time on my mac with Venture 13.4. It worked up until the latest update.

**Comment by DudeNr33** [comment]
Thank you for the report. I haven't installed 13.4 yet, but will look into it as soon as possible.
Can you describe a bit more in detail what is wrong with the computed total time?

**Comment by shoaibhussain-uc** [comment]
It seems the output from the pmset -g log command has changed and the script isn't able to parse it correctly. The total screen time was an unrealistic value and the time of the last charge wasn't correctly reported. 
I really liked the convenience of seeing the total screen time with this script when it worked. Thanks for the project!

**Comment by stefanmaric** [comment]
I opened a few PRs addressing some issues I encountered while using this script in my 15" Air.

At this point, I haven't found any more issues but would be worth it for others to try it.

**Comment by DudeNr33** [comment]
@stefanmaric thank you for the fixes!
@shoaibhussain-uc can you tell me if this fixes the issue(s) you encountered?
If not, it would be very helpful if you could copy the full output and paste it here. 

One thing I noticed which is still present: I had a negative percentage under "statistics" when I ran the script while the laptop was plugged in.

**Comment by shoaibhussain-uc** [comment]
> @stefanmaric thank you for the fixes! @shoaibhussain-uc can you tell me if this fixes the issue(s) you encountered? If not, it would be very helpful if you could copy the full output and paste it here.
> 
> One thing I noticed which is still present: I had a negative percentage under "statistics" when I ran the script while the laptop was plugged in.

Hi, I just ran the script and the numbers seem fine now. Previously the 'unplugged from AC' time wasn't aligned with the time in battery settings.

**Comment by DudeNr33** [comment]
Great! Probably https://github.com/DudeNr33/screen-on-time/pull/7 solved the issue. 👍 
Feel free to reopen if the problem occurs again.
